name: Build and Deploy Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Update Poetry
        run: poetry self update -vv
      - name: Install Project Dependencies
        run: poetry install -vv
      - name: Build Site
        run: make html
      - name: Extract Project Version
        uses: mathiasvr/command-output@v1
        id: version
        with:
          run: poetry version -s
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/html
          target-folder: dev/${{ steps.version.outputs.stdout }}
