name: Build and Deploy Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Extract Branch Name
        uses: mathiasvr/command-output@v1
        id: branch
        with:
          run: echo ${GITHUB_REF#refs/heads/}
      - name: Install Poetry
        run: pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Update Poetry
        run: poetry self update -vv
      - name: Install Project Dependencies
        run: poetry install -vv
      - name: Build Site
        run: poetry run sphinx-build -M html source build
      - name: Extract Project Version
        uses: mathiasvr/command-output@v1
        id: version
        with:
          run: poetry version -s
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          force_orphan: true
          destination_dir: ${{ steps.branch.outputs.stdout }}/${{ steps.version.outputs.stdout }}
          enable_jekyll: true
          allow_empty_commit: true
