name: Build and Deploy Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Set branch name
        id: branch
        run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"
      - name: Install Poetry
        run: pipx install poetry
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Update Poetry
        run: poetry self update -vv
      - name: Install Project Dependencies
        run: poetry install -vv
      - name: Extract Project Version
        id: version
        run: echo "::set-output name=PROJECT_VERSION::$(poetry version -s)"
      - name: Build Site
        run: poetry run sphinx-build -M html source build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          force_orphan: true
          destination_dir: ${( steps.branch.outputs.BRANCH_NAME }}/${( steps.version.outputs.PROJECT_VERSION }}
          enable_jekyll: true
          allow_empty_commit: true
